
/*============================================================================
Filename : touch_api_ptc.h
Project : QTouch Modular Library
Purpose : Includes the Module API header files based on the configured modules,
          prototypes for touch.c file and Application helper API functions

This file is part of QTouch Modular Library Release 7.5 application.

Important Note: Do not edit this file manually.
                Use QTouch Configurator within Atmel Start to apply any
                modifications to this file.

Usage License: Refer license.h file for license information
Support: Visit http://www.microchip.com/support/hottopics.aspx
               to create MySupport case.

------------------------------------------------------------------------------
Copyright (c) 2021 Microchip. All rights reserved.
------------------------------------------------------------------------------
============================================================================*/

#ifndef TOUCH_API_PTC_H
#define TOUCH_API_PTC_H

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/*----------------------------------------------------------------------------
 *     include files
 *----------------------------------------------------------------------------*/
void touch_timer_handler(void);

#ifdef __cplusplus
}
#endif

#endif /* TOUCH_API_PTC_H */
